 
// the configured options and settings for raw2dng
#define RAW2DNG_VERSION_MAJOR 1
#define RAW2DNG_VERSION_MINOR 2
#define RAW2DNG_VERSION_PATCH 2

#define RAW2DNG_VERSION_MAKE(a,b,c) #a"."#b"."#c
#define _RAW2DNG_VERSION_MAKE(a,b,c) RAW2DNG_VERSION_MAKE(a,b,c)
#define RAW2DNG_VERSION_STR _RAW2DNG_VERSION_MAKE(RAW2DNG_VERSION_MAJOR,RAW2DNG_VERSION_MINOR,RAW2DNG_VERSION_PATCH)
